### PR TITLE
Expose consumer creation failures

### LINKED ISSUE #612: Improve handling of misconfigured Kafka client
The `KafkaConsumerActor` can do better in situations where the `ConsumerSettings` are not complete:
1. don't have bootstrap servers (fails in preStart)
1. don't have a group id (fails during poll)

### PR DESCRIPTION
**Pull request by ennru**
Catch exceptions in the actor and send them as `Status.Failure` to known stage actors so that the stream can fail with the appropriate error.

* Pass creating stage's ActorRef to consumer actor (owner)
* Catch Kafka Consumer creation exceptions and pass to owner
* Catch exceptions in poll's outer catch clause

Fixes #612

### CODE REVIEW

**Comment by ennru** [comment]
Fixes #542

File: core/src/main/scala/akka/kafka/internal/BaseSingleSourceLogic.scala [hunk 1]
```diff
@@ -52,11 +49,12 @@ private[kafka] abstract class BaseSingleSourceLogic[K, V, Msg](
...
         }
         pump()
-      case (_, Failure(e)) =>
+      case (_, Status.Failure(e)) =>
         failStage(e)
       case (_, Terminated(ref)) if ref == consumerActor =>
         failStage(new ConsumerFailed())
     }
+    consumerActor = createConsumerActor()
     sourceActor.watch(consumerActor)
```
Comment (2m) [inline core/src/main/scala/akka/kafka/internal/BaseSingleSourceLogic.scala]: `watch` returns the same `ActorRef` that it gets. So it is possible to rewrite this with:

```scala
consumerActor = sourceActor.watch(createConsumerActor())
```

Comment (ennru) [reply core/src/main/scala/akka/kafka/internal/BaseSingleSourceLogic.scala]: No, it is `Unit` typed.

Comment (2m) [reply core/src/main/scala/akka/kafka/internal/BaseSingleSourceLogic.scala]: Ahh, `sourceActor` is a stage sctor. Well that is unfortunate that the API differs.
