### PR TITLE
Tests: Call commit callbacks in ConsumerMock poll

### LINKED ISSUE #895: [Failed] CommittingWithMockSpec should collect commits to be sent to commitAsync
```
[info] CommittingWithMockSpec:

[info] - should commit metadata in message (469 milliseconds)

[info] - should call commitAsync for commit message and then complete future (228 milliseconds)

[info] - should fail future in case of commit fail (220 milliseconds)

[info] - should collect commits to be sent to commitAsync *** FAILED *** (10 seconds, 101 milliseconds)

[info]   java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]

[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)

[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)

[info]   at scala.concurrent.Await$.$anonfun$result$1(package.scala:220)

[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)

[info]   at scala.concurrent.Await$.result(package.scala:146)

[info]   at akka.kafka.internal.CommittingWithMockSpec.$anonfun$new$13(CommittingWithMockSpec.scala:229)
```

https://travis-ci.org/akka/alpakka-kafka/jobs/581091376#L827

### PR DESCRIPTION
**Pull request by seglo**
While investigating a cause for failures in the flakey test `collect commits to be sent to commitAsync` I observed that the `ConsumerMock` commit callback logic was always executed in the test thread, instead of the `KafkaConsumerActor.poll` thread. This caused internal in-flight commit callback book keeping to sometimes get into an error state due to race conditions.  I moved the "commit emulation" steps of all the tests in `CommittingWithMockSpec` to occur during the `ConsumerMock.poll` call, which simulates what happens in a real consumer.  I added new assertions to wait until all outstanding commit requests have been completed (have been polled), and an overload to wait until some minimum offset has been committed.

This _should_ fix #895.

### CODE REVIEW

File: tests/src/test/scala/akka/kafka/internal/CommittingWithMockSpec.scala [hunk 1]
```diff
@@ -67,19 +66,8 @@ class CommittingWithMockSpec(_system: ActorSystem)
...
-    val (control, probe) = createCommittableSource(mock.mock)
-      .toMat(TestSink.probe)(Keep.both)
-      .run()
-
-    probe.request(msgss.map(_.size).sum.toLong)
-    msgss.foreach(chunk => mock.enqueue(chunk.map(toRecord)))
-    probe.expectNextN(msgss.flatten)
-
-    Await.result(control.shutdown(), remainingOrDefault)
-  }
```
Comment (seglo) [inline tests/src/test/scala/akka/kafka/internal/CommittingWithMockSpec.scala:82]: This no longer has any usages.

File: tests/src/test/scala/akka/kafka/internal/CommittingWithMockSpec.scala [hunk 2]
```diff
@@ -224,23 +206,11 @@ class CommittingWithMockSpec(_system: ActorSystem)
...
-      commitLog.calls.foreach {
-        case (offsets, callback) =>
-          // What is the highest offset recorded in this callback?
-          val max = offsets.map { case (key, value) => value.offset() }.max
-          // update lastOffsetObserved
-          lastOffsetObserved = Math.max(lastOffsetObserved, max)
-          callback.onComplete(offsets.asJava, null)
-      }
-      lastOffsetObserved should be >= count.toLong
-    }
```
Comment (seglo) [inline tests/src/test/scala/akka/kafka/internal/CommittingWithMockSpec.scala:240]: This behaviour is effectively rolled back to what existed before #1047

**Comment by ennru** [comment]
Great!
